name: Deploy Flask App to Azure

# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

# Define the job to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Test your code (optional, for testing)
      - name: Run tests
        run: |
          pytest # Or any other test framework you're using (e.g., unittest)

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: HDB-Forecasting  # Replace with your Azure App Service name
          slot-name: production  # Optionally specify a slot if you're using deployment slots
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Azure publish profile from GitHub secrets
